### ISSUE TITLE
Dovecot config is not actually including the conf.d/ files

### ISSUE THREAD

**Issue by jeroenrnl** [technicalguru/docker-mailserver-postfix#31]
```
!include conf.d/*.conf
```
is missing from `dovecot.conf`

**Comment by jeroenrnl** [comment]
Adding the include will completely break the setup, unfortunately, because there are quite a few files in the standard setup that will inject erroneous settings into the config, they will all need to be overridden.
Let me know if you want me to come up with a pull request.

**Comment by technicalguru** [comment]
Released with 3.7.9.1
